# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: tootsuite/mastodon
  tag: latest
  pullPolicy: Always
podAnnotations: {}
application:
  secretName:
  web:
    initializeCommand: bundle exec rails db:migrate
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
service:
  media:
    enabled: true
    type: ExternalName
    externalName: ""
  streaming:
    enabled: true
    annotations: {}
    type: ClusterIP
    externalPort: 4000
    internalPort: 4000
  web:
    enabled: true
    annotations: {}
    type: ClusterIP
    externalPort: 3000
    internalPort: 3000
ingress:
  enabled: true
  tls:
    enabled: true
    secretName: ""
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
  media:
    commonName:
  web:
    commonName:
livenessProbe:
  path: "/_/ping"
  initialDelaySeconds: 15
  timeoutSeconds: 15
  scheme: "HTTP"
readinessProbe:
  path: "/_/ping"
  initialDelaySeconds: 5
  timeoutSeconds: 3
  scheme: "HTTP"
postgresql:
  enabled: true
resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
  requests:
#    cpu: 100m
#    memory: 128Mi

## Configure PodDisruptionBudget
## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
#
podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  maxUnavailable: 1

otpSecret: ""
secretKeyBase: ""
vapidPrivateKey: ""
vapidPublicKey: ""

awsAccessKeyId: ""
awsSecretAccessKey: ""
cdnHost: ""
databaseUrl: ""
externalMediaHost: ""
localDomain: ""
redisHost: redis
redisPort: 6379
smtpServer: localhost
smtpPort: 587
smtpLogin: ""
smtpPassword: ""
smtpFromAddress: notifications@example.com
s3AliasHost: ""
s3Enabled: false
s3Bucket: ""
s3Endpoint: ""

redis:
  cluster:
    enabled: false
  master:
    podAnnotations:
      linkerd.io/inject: enabled
