apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-streaming
  annotations:
    linkerd.io/inject: enabled
  labels:
    app: mastodon
    component: streaming
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mastodon
      component: streaming
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        app: mastodon
        component: streaming
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-streaming
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
            - node
            - ./streaming
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-{{ .Chart.Name }}-config
        {{- if .Values.application.secretName }}
        - secretRef:
            name: {{ .Values.application.secretName }}
        {{- end }}
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-redis
              key: redis-password
        ports:
        - name: streaming
          containerPort: {{ .Values.service.streaming.internalPort }}
        livenessProbe:
          httpGet:
            path: /api/v1/streaming/health
            port: {{ .Values.service.streaming.internalPort }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: /api/v1/streaming/health
            port: {{ .Values.service.streaming.internalPort }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
