apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.secretName }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.awsAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsSecretAccessKey | b64enc | quote }}
  DATABASE_URL: {{ .Values.databaseUrl | b64enc | quote }}
  OTP_SECRET: {{ .Values.otpSecret | b64enc | quote }}
  SECRET_KEY_BASE: {{ .Values.secretKeyBase | b64enc | quote }}
  SMTP_PASSWORD: {{ .Values.smtpPassword | b64enc | quote }}
  VAPID_PRIVATE_KEY: {{ .Values.vapidPrivateKey | b64enc | quote }}
  VAPID_PUBLIC_KEY: {{ .Values.vapidPublicKey | b64enc | quote }}
